apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aoc2021-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          # Dummy service
          - path: /foo
            pathType: Prefix
            backend:
              service:
                name: foo
                port:
                  number: 8080
          - path: /sonar-sweep(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: sonar-sweep
                port:
                  number: 8080
          - path: /dive(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: dive
                port:
                  number: 8080
          - path: /binary-diagnostic(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: binary-diagnostic
                port:
                  number: 8080
          - path: /giant-squid(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: giant-squid
                port:
                  number: 8080
          - path: /hydrothermal-venture(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: hydrothermal-venture
                port:
                  number: 8080
          - path: /lanternfish(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: lanternfish
                port:
                  number: 8080
          - path: /the-treachery-of-whales(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: the-treachery-of-whales
                port:
                  number: 8080
          - path: /seven-segment-search(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: seven-segment-search
                port:
                  number: 8080
          - path: /smoke-basin(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: smoke-basin
                port:
                  number: 8080
          - path: /syntax-scoring(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: syntax-scoring
                port:
                  number: 8080
          - path: /dumbo-octopus(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: dumbo-octopus
                port:
                  number: 8080
          - path: /passage-pathing(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: passage-pathing
                port:
                  number: 8080
          - path: /transparent-origami(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: transparent-origami
                port:
                  number: 8080
          - path: /extended-polymerization(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: extended-polymerization
                port:
                  number: 8080
          - path: /chiton(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: chiton
                port:
                  number: 8080
          - path: /packet-decoder(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: packet-decoder
                port:
                  number: 8080
          - path: /trick-shot(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: trick-shot
                port:
                  number: 8080
          - path: /snailfish(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: snailfish
                port:
                  number: 8080
          - path: /beacon-scanner(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: beacon-scanner
                port:
                  number: 8080
          - path: /trench-map(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: trench-map
                port:
                  number: 8080
          - path: /dirac-dice(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: dirac-dice
                port:
                  number: 8080
          - path: /reactor-reboot(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: reactor-reboot
                port:
                  number: 8080
          - path: /amphipod(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: amphipod
                port:
                  number: 8080
          # Add more...
